# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 04:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Projetor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('status', models.BooleanField(default=True)),
                ('manutencao', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, max_length=256, verbose_name='descricao')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetores', to='board.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('data_de_saida', models.DateTimeField(verbose_name='Data de entrada')),
                ('observacao', models.TextField(blank=True, max_length=256, verbose_name='descricao')),
                ('data_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao', to='board.Projetor')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='board.Professor')),
            ],
        ),
    ]
