# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 22:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_horario_devolucao', models.DateTimeField(null=True, verbose_name='Devolucao')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Devoluçao',
                'verbose_name_plural': 'Devoluçoes',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Professor(a)',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Projetor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('status', models.CharField(choices=[('D', 'Disponivel'), ('M', 'Manutenção'), ('U', 'Uso'), ('R', 'Reservado')], max_length=1, verbose_name=(('D', 'Disponivel'), ('M', 'Manutenção'), ('U', 'Uso'), ('R', 'Reservado')))),
                ('observacao', models.TextField(blank=True, max_length=256, verbose_name='descricao')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetores', to='board.Departamento')),
            ],
            options={
                'verbose_name': 'Projetor',
                'verbose_name_plural': 'Projetores',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('observacao', models.TextField(blank=True, max_length=256, verbose_name='descricao')),
                ('data_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao', to='board.Projetor')),
                ('devolucao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Devolucao')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='board.Professor')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
