# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='cod_datashow',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_show',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao', to='board.Projetor'),
            preserve_default=False,
        ),
    ]
