# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170818_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
