# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170824_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetor',
            name='status',
            field=models.CharField(choices=[('D', 'Disponivel'), ('M', 'Manutenção'), ('U', 'Uso'), ('R', 'Reservado')], default='D', max_length=1, verbose_name='Status'),
        ),
    ]
