# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20170824_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetor',
            name='manutencao',
            field=models.BooleanField(default=False),
        ),
    ]
