# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20170823_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='dt_horario_devolucao',
            field=models.DateTimeField(null=True, verbose_name='Devolucao'),
        ),
    ]
